/* ================================================================
 * thai_fonts.h - Thai font declarations
 *
 * Custom Thai fonts ported from ESP32 project.
 * Generated from Sarabun-Regular.ttf via LVGL font converter.
 *
 * Range: ASCII 32-127 + Thai 0x0E00-0x0E7F (3584-3711)
 * Format: 4 bpp (anti-aliased)
 * ================================================================ */
#pragma once

#include "lvgl/lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Thai Sarabun font, 24px, 4bpp.
 * Regular variant — use for plain text without vowel/tone stacking. */
LV_FONT_DECLARE(thai_sarabun_24);

/* Stacked variant — tone marks raised +6 px to clear vowel-above stacks
 * like ขึ้น (ึ + ้), ที่ (ี + ่), นี้ (ี + ้), รู้ (ู + ้). Same ASCII +
 * Thai range as the regular variant; line_height = 38 (vs 34). Phase
 * 2.2.5d: swept across all UI labels for consistency. */
LV_FONT_DECLARE(thai_sarabun_stacked_24);

/* 48 px native — used for the header branding label "บริษัท เลเซอร์เอ็น
 * จิเนียร์ จำกัด". Sized between the body text (24) and the clock-height
 * title (72) so the branding reads as a heading without overflowing the
 * header bar or crowding the clock at TOP_MID. ~395 KB. */
LV_FONT_DECLARE(thai_sarabun_48);

/* 72 px native — used for the mini-calendar title "พฤษภาคม 2569" so it
 * renders sharp at clock-matched height instead of being bitmap-scaled
 * 3x from the 24 px variant (which produced visibly aliased edges).
 * Generated by `generate_fonts.ps1` from Sarabun-Regular.ttf. ~830 KB.
 * No stacked variant needed — Thai month names + Buddhist year digits
 * have no vowel/tone-mark stacking. */
LV_FONT_DECLARE(thai_sarabun_72);

#ifdef __cplusplus
}
#endif
